config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'home#index'

  get 'home/index'

  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resource :admin, param: :user_id, only: %i[show destroy update]
  resource :director, param: :user_id, only: %i[show update]

  get '/user/existence/:email', to: 'users#email_uniq?', constraints: { email: /.+\..+/}

  namespace :vacancy do
    resources :attributes, param: :attr_id, except: %i[show new]
    resources :country_search, only: %i[index]
    resources :requests, only: %i[index create]
  end

  namespace :user do
    get '/vacancies', to: 'vacancies#index'
    resource :skill_level, only: %i[edit]
    resource :education, only: %i[edit update]
  end

  resource :manager, param: :user_id, only: %i[show]
  resources :vacancies, param: :vac_id, except: %i[edit]
  resources :users, param: :user_id, except: %i[index new show]
  resources :profiles, param: :user_id, only: %i[show edit update]
  resources :password_resets, only: %i[create edit update]
  resources :account_activations, only: %i[edit]
end

app/models/user/education.rb
# frozen_string_literal: true

class User
  class Education < ApplicationRecord
    belongs_to :user

    validates :university, presence: true, length: { minimum: 3, maximum: 15 }
    validates :faculty, presence: true, length: { minimum: 2, maximum: 15 }
    validates :department, presence: true, length: { minimum: 3, maximum: 15 }
    validates :graduation_year, presence: true,
                                numericality: { greater_than: 1955,
                                                less_than: 2025 }
    validates :entrance_year, presence: true,
                              numericality: { greater_than: 1950,
                                              less_than: :graduation_year }

    ENGLISH = %w[A0-(Beginner) A1(Elementary) A2(Pre-Intermediate)
                 B1(Intermediate) B2(Upper-Intermediate) C1(Advanced)].freeze
  end
end

app/controllers/user/educations_controller.rb
# frozen_string_literal: true

class User
  class EducationsController < ApplicationController
    def edit
      @education = current_user.education
    end

    def update
      @education = current_user.education

      if @education.update_attributes(education_params)
        redirect_to profile_path(current_user)
      else
        render :edit
      end
    end

    private

    def education_params
      params.require(:user_education).permit(:university, :faculty, :department,
                                             :entrance_year, :graduation_year,
                                             :english_level)
    end
  end
end

app/views/educations/_show.html.slim
div id="education"
  div class="bloktron" id="education-info-head"
    div class="container"
      h1
        | Education information  
  div class="bloktron" id="education-info"
    p class="lead"
      | University: #{@education.university}
      br
      | Faculty: #{@education.faculty}
      br
      | Department: #{@education.department}
      br
      | Entrance year: #{@education.entrance_year}
      br
      | Graduation year: #{@education.graduation_year}
      br
      | English level: #{@education.english_level}
    = link_to 'Edit', edit_education_path(current_user), :class => 'btn btn-lg btn-primary', :id => 'edit_button'

app/views/educations/edit.html.slim
main role="main" class="container" id="education"
        div class="bloktron" id="education-head-edit"
          div class="container"
            h1
              | Editing education information
        div class="bloktron" id="education-info-edit"
            = form_for(@education) do |f|
                = render 'shared/register_error_messages', object: @education
                div class="field"
                = f.label :university
                = f.text_field :university, placeholder: 'The name of your university', :class => 'form-control'
                div class="field"
                = f.label :faculty
                = f.text_field :faculty, placeholder: 'The name of your faculty', :class => 'form-control'
                div class="field"
                = f.label :department
                = f.text_field :department, placeholder: 'The name of your department', :class => 'form-control'
                div class="field"
                = f.label :entrance_year
                = f.number_field :entrance_year, placeholder: '2000', :class => 'form-control'
                div class="field"
                = f.label :graduation_year
                = f.number_field :graduation_year, placeholder: '2005', :class => 'form-control'
                div class="field"
                = f.label :english_level
                br
                = select(:education, :english_level, Education::ENGLISH)
                br
                br
                div class="actions"
                = f.submit "Edit education", :class => 'btn btn-primary'

app/views/educations/show.html.slim
div
  p
    | Education with id
    = @education.id
  p
    | Highschool: 
    = @education.highschool
  p
    | Faculty: 
    = @education.faculty
  p
    | Department: 
    = @education.department
  p
    | Start year: 
    = @education.year_of_start
  p
    | End year: 
    = @education.year_of_end
  p
    | English level: 
    = @education.english
div
  = link_to :edit, edit_education_path